"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q@t37wt$)7=%xh^a@h_-@6+j$y=ot1yo*+xd5sxkoo#n7gk2(!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendas',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'  # Muda o idioma de 'en-us' para Português do Brasil

TIME_ZONE = 'America/Sao_Paulo'  # Ajusta o fuso horário oficial

USE_I18N = True

USE_TZ = True
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os

# No final do arquivo:
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# REDIRECIONAMENTOS DE AUTENTICAÇÃO
LOGIN_REDIRECT_URL = 'vitrine'   # Para onde ir após fazer login (Home)
LOGOUT_REDIRECT_URL = 'vitrine'  # Para onde ir após sair
LOGIN_URL = 'login'              # Nome da nossa rota de login

# No servidor real (Produção), usaremos um serviço de e-mail de verdade
# Configuração para envio de e-mails reais via Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'aircodeproject@gmail.com'
EMAIL_HOST_PASSWORD = 'gmvuoyutgwkoqibz' # Sem espaços entre as letras
DEFAULT_FROM_EMAIL = 'Silver & Gold Online <aircodeproject@gmail.com>'

# Tempo da sessão em segundos (ex: 600s = 10 minutos)
SESSION_COOKIE_AGE = 600

# Faz com que a sessão expire quando o navegador fechar
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Atualiza o tempo de expiração a cada novo clique (reinicia os 10 min)
SESSION_SAVE_EVERY_REQUEST = True

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --- CONFIGURAÇÕES DO AXES ---
AXES_FAILURE_LIMIT = 5            # Bloqueia após 5 tentativas erradas
AXES_COOLOFF_TIME = 1             # O bloqueio dura 1 hora
AXES_LOCKOUT_TEMPLATE = 'vendas/erro_bloqueio.html' # Tela personalizada
AXES_RESET_ON_SUCCESS = True      # Se acertar a senha, as falhas anteriores são zeradas
AXES_LOCKOUT_PARAMETERS = ["username"]    # Bloqueia APENAS o usuário, liberando o IP para os outros
AXES_W006_CONF_VAR_OR_IP_ADDRESS_CHECK_ENABLED = False




