# Generated by Django 6.0.3 on 2026-03-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Joia')),
                ('tipo_metal', models.CharField(choices=[('OURO', 'Ouro'), ('PRATA', 'Prata')], max_length=5, verbose_name='Metal')),
                ('peso_gramas', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso (g)')),
                ('pureza', models.DecimalField(decimal_places=3, default=0.75, help_text='Ex: 0.750 para 18k ou 0.925 para Prata', max_digits=5)),
                ('custo_mao_de_obra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mão de Obra (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=1.3, help_text='1.30 = 30% de lucro', max_digits=5)),
                ('preco_venda_atual', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
            ],
        ),
    ]
