# Generated by Django 6.0.3 on 2026-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('aneis', 'Anéis'), ('brincos', 'Brincos'), ('correntes', 'Correntes'), ('pulseiras', 'Pulseiras'), ('pingentes', 'Pingentes')], default='aneis', max_length=20, verbose_name='Categoria'),
        ),
    ]
