# Generated by Django 6.0.3 on 2026-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_oportunidade',
            field=models.BooleanField(default=False, verbose_name='É Oportunidade?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Promocional (Opcional)'),
        ),
    ]
