# Generated by Django 6.0.3 on 2026-03-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_produto_is_oportunidade_produto_preco_promocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Para a URL (ex: aneis-de-ouro)', unique=True)),
                ('icone', models.CharField(blank=True, help_text='Ícone (ex: fas fa-ring)', max_length=50, null=True)),
                ('banner_imagem', models.ImageField(blank=True, null=True, upload_to='categorias/banners/', verbose_name='Banner da Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='vendas.categoria', verbose_name='Categoria'),
        ),
    ]
