# Generated by Django 6.0.3 on 2026-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_cliente_cpf_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Dia das Mães', max_length=100)),
                ('subtitulo', models.CharField(help_text='Ex: O presente perfeito...', max_length=255)),
                ('imagem_url', models.URLField(help_text='Link direto da imagem (Unsplash ou outro)')),
                ('texto_botao', models.CharField(default='Ver Coleção', max_length=50)),
                ('link_destino', models.CharField(default='#vitrine', max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (0, 1, 2...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Banner de Campanha',
                'verbose_name_plural': 'Banners de Campanha',
                'ordering': ['ordem'],
            },
        ),
    ]
